version: "3.8"

services:
  tasks-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpassword
      POSTGRES_DB: taskdb
    ports:
      - "5433:5433"
    volumes:
      - data:/var/lib/postgresql/data

  tasks-app:
    container_name: tp_integration_continue
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - tasks-db
    environment:
      - DATABASE_URL=postgresql://taskuser:taskpassword@tasks-db/taskdb

  # tasks-test:
  #   build: .
  #   depends_on:
  #     - tasks-db
  #   environment:
  #     - DATABASE_URL=postgresql://taskuser:taskpassword@tasks-db/taskdb
  #     - TEST_DATABASE_URL=postgresql://taskuser:taskpassword@tasks-db/taskdb_test
  #   command: ["pytest", "--cov=app"]

volumes:
  data: