name: CI Pipeline

on: [push, pull_request]

jobs:
  ci-pipeline:
    name: CI Pipeline
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint code
      run: |
        # Lint Python code
        pylint app/*.py
        # Lint Dockerfile
        docker run --rm hadolint/hadolint < Dockerfile
        # Lint dependencies
        pip check

    - name: Set up Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
        docker-compose ps
        sleep 50  # Wait a few seconds to ensure services are started

    - name: Run unit tests with coverage
      env:
        DATABASE_URL: postgresql://taskuser:taskpassword@tasks-db/taskdb
      run: |
        pytest tests --cov=app

    - name: Stop Docker Compose services
      run: docker-compose -f docker-compose.yml down
