name: CI

on:
  push:
    branches:
      - main

jobs:
  test-docker-container:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          
      - name: Pull Docker image
        run: |
          docker pull ritacarrilho/tp_integration_continue:latest

      - name: Run Docker container
        run: |
          docker run -d --name tp_integration_continue -p 8000:8000 ritacarrilho/tp_integration_continue:latest
          sleep 15  # Attendre que le conteneur démarre
          
      - name: Check if FastAPI started successfully
        run: |
          curl -f http://127.0.0.1:8000 || exit 1

      - name: Stop Docker container
        if: always()
        run: |
          docker stop tp_integration_continue
          docker rm tp_integration_continue
