name: CI

on:
  push:
    branches:
      - main

jobs:
  test-fastapi-start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start FastAPI server
        run: |
          uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          sleep 5  # Attendre que le serveur démarre

      - name: Check if FastAPI started successfully
        run: |
          curl -f http://127.0.0.1:8000 || exit 1
        env:
          CI: true
